version: '2'
services:
  db:
    image: mysql:5.6
    environment:
        - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3340:3306"
  mail:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "WEB_DOCUMENT_ROOT=/app/public"
      - FUEL_ENV=development
      - RDS_HOSTNAME=db
      - RDS_PORT=3306
      - RDS_DB_NAME=ebdb
      - RDS_USERNAME=root
      - RDS_PASSWORD=root
      - CMS_ADDR=iacc-cms.elasticbeanstalk.com:80
      - CMS_AUTH_KEY=f1e446e0292fd6d8a7a4365a115adf69
      - CMS_SITE_ID=PPS
      - API_ENDPOINT=https://h2xmfbiaa8.execute-api.ap-northeast-1.amazonaws.com/development
      - TWILLIO_AUTH_TOKEN=693a15e0708e521d9cf8dbeee8fb097a
      - "TWILLIO_ACCOUNT_SID=ACedda9750010d541d955c58564b7403b1"
      - "TWILLIO_TEL_FROM=+815031887682"
      - "TWILLIO_SMS_FROM=+12027967716"
      - AWS_ACCESS_KEY_ID=AKIAI2NFTZUSEGDK5E4Q
      - AWS_SECRET_ACCESS_KEY=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
      - S3_BUCKET=enepi
    volumes:
      - ./:/app
    ports:
      - "8080:80"
    expose:
      - "80"
    depends_on:
      - db
      - mail
