<form class="simple_form edit_new_year_holiday" id="edit_new_year_holiday_1" action="/admin/new_year_holiday" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="_method" value="put"><input type="hidden" name="authenticity_token" value="v3l63wjdSTeVHcK5OLtGyi9FkThbeflX5nlavob2+9VK6KGdY/9AKRlEa4fb5p8HalndcgS8XOMRmpyr2eVHtA==">
  
  <div class="form-group string required new_year_holiday_beg_at"><label class="string required control-label" for="new_year_holiday_beg_at"><abbr title="required">*</abbr> 開始日</label><input class="string required datepicker form-control" required="required" aria-required="true" type="text" value="2016-12-26 00:00:00 +0900" name="new_year_holiday[beg_at]" id="new_year_holiday_beg_at"></div>
  <div class="form-group string required new_year_holiday_end_at"><label class="string required control-label" for="new_year_holiday_end_at"><abbr title="required">*</abbr> 終了日</label><input class="string required datepicker form-control" required="required" aria-required="true" type="text" value="2017-01-03 00:00:00 +0900" name="new_year_holiday[end_at]" id="new_year_holiday_end_at"></div>
  <div class="form-group text required new_year_holiday_holiday_text"><label class="text required control-label" for="new_year_holiday_holiday_text"><abbr title="required">*</abbr> 文言</label><textarea class="text required form-control" required="required" aria-required="true" name="new_year_holiday[holiday_text]" id="new_year_holiday_holiday_text">2016年12月28日(水)より2017年1月3日(火)までの年末年始の間、
お見積もりに通常よりお時間を頂く可能性がございます。ご了承ください。</textarea></div>
  <div class="form-group text required new_year_holiday_holiday_email_contact"><label class="text required control-label" for="new_year_holiday_holiday_email_contact"><abbr title="required">*</abbr> メール文言(問い合わせ)</label><textarea class="text required form-control" required="required" aria-required="true" name="new_year_holiday[holiday_email_contact]" id="new_year_holiday_holiday_email_contact">なお、年末年始期間のためご連絡が休業期間明けになることもございます。予めご容赦くださいますようお願い申し上げます。</textarea></div>
  <div class="form-group text required new_year_holiday_holiday_email_estimate_ok"><label class="text required control-label" for="new_year_holiday_holiday_email_estimate_ok"><abbr title="required">*</abbr> メール文言(送客)</label><textarea class="text required form-control" required="required" aria-required="true" name="new_year_holiday[holiday_email_estimate_ok]" id="new_year_holiday_holiday_email_estimate_ok">なお、年末年始期間のため場合によっては、ガス会社からのご連絡が休業期間明けになることもございます。予めご容赦くださいますようお願い申し上げます。</textarea></div>
  <input type="submit" name="commit" value="更新する" class="btn btn-default">
</form>
